version: '3.9'

volumes:
  mongo_data:
    driver: local
  seq_data:
    driver: local

services: 
  api:
    build:
      context: .
      dockerfile: backend/src/Todo.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=9000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_URLS=https://+;http://+
      - Identity__BaseAddress=http://identity
      - Identity__BaseAddressSwagger=https://localhost:9002
      - Mongo__ConnectionString=mongodb://mongo:27017/todo-api
      - Seq__ServerUrl=http://seq:5341
    ports:
      - "9000:443"
      - "9001:80"
    profiles:
      - backend
      - all
    volumes:
      - ~/.aspnet/https:/https:ro
  
  todo-portal:
    command: "npm start"
    build:
      context: .
      dockerfile: ./todo-portal/Dockerfile
    volumes:
      - "./frontend/todo-portal:/app"
      - "/app/node_modules"
    ports:
      - "9004:9004"
    profiles:
      - all
    environment:
      - CHOKIDAR_USEPOLLING=true

  seq:
    container_name: seq
    image: datalust/seq:latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    profiles:
      - backend
      - services
      - all
    volumes:
      - ./backend/logs:/data
  
  mongo:
    image: mongo
    profiles:
      - backend
      - services
      - all
    ports:
      - "27017:27017"
    
  identity:
    build:
      context: .
      dockerfile: backend/Todo.Identity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=9002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_URLS=https://+;http://+
      - Mongo__ConnectionString=mongodb://mongo:27017/todo-api
      - Seq__ServerUrl=http://seq:5341
    ports:
      - "9002:443"
      - "9003:80"
    profiles:
      - backend
      - all
    volumes:
      - ~/.aspnet/https:/https:ro