version: '3.9'

volumes:
  mongo_data:
    driver: local
  seq_data:
    driver: local

services: 
  api:
    build:
      context: .
      dockerfile: ./src/Todo.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=9000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_URLS=https://+;http://+
      - Identity__BaseAddress=http://identity
      - Identity__BaseAddressSwagger=https://localhost:9002
      - Mongo__ConnectionString=mongodb://mongo:27017/todo-api
      - Seq__ServerUrl=http://seq:5341
    ports:
      - "9000:443"
      - "9001:80"
    profiles:
      - backend
      - all
    volumes:
      - ~/.aspnet/https:/https:ro
  
  seq:
    container_name: seq
    image: datalust/seq:latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    profiles:
      - backend
      - services
      - all
    volumes:
      - /Users/maxwallwey/code/maxwallwey-todo/backend/logs:/data
  
  mongo:
    image: mongo
    profiles:
      - backend
      - services
      - all
    ports:
      - "27017:27017"