name: ci

on:
  push:
    paths-ignore: ["**.md"]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  ci:
    name: ${{ matrix.os }} CI
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install task
      uses: arduino/setup-task@v1

    - name: Build dotnet and run tests
      run: task ci

    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: ${{ matrix.os }} Test Results
        path: "**/TestResults/test-results.trx"
        reporter: dotnet-trx

    - name: Generate test coverage report
      uses: 5monkeys/cobertura-action@master
      if: success() || failure()
      with:
        path: "**/TestResults/*/*.xml"
        link_missing_lines: true
        minimum_coverage: 75
        report_name: ${{matrix.os}} test coverage report
        show_line: true
        show_class_names: true
        show_missing: true
        skip_covered: false
